import { MigrationInterface, QueryRunner } from 'typeorm';

export class DocumetReview1723741735944 implements MigrationInterface {
  name = 'DocumetReview1723741735944';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "DOCUMENT_REVIEWS"
                             (
                                 "ID"              number GENERATED BY DEFAULT AS IDENTITY,
                                 "UUID"            varchar2(36) NOT NULL,
                                 "CREATED_AT"      timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "UPDATED_AT"      timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "DOCUMENT_ID"     number                              NOT NULL,
                                 "REVIEWABLE_ID"   number                              NOT NULL,
                                 "REVIEWABLE_TYPE" varchar2(255) NOT NULL,
                                 "REMARK"          varchar2(255),
                                 "STATUS"          varchar2(255),
                                 "REVIEWER_ID"     number,
                                 CONSTRAINT "UQ_8cf08c7a26839e9284f4f1cf266" UNIQUE ("UUID"),
                                 CONSTRAINT "PK_539678b9fe5d52ac30167354718" PRIMARY KEY ("ID")
                             )`);
    await queryRunner.query(`ALTER TABLE "DOCUMENT_REVIEWS"
        ADD CONSTRAINT "FK_d93e6792500416b5370f780b5ad" FOREIGN KEY ("REVIEWER_ID") REFERENCES "USERS" ("ID")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "DOCUMENT_REVIEWS" DROP CONSTRAINT "FK_d93e6792500416b5370f780b5ad"`,
    );
    await queryRunner.query(`DROP TABLE "DOCUMENT_REVIEWS"`);
  }
}
