import { MigrationInterface, QueryRunner } from 'typeorm';

export class AuditLog1724757388002 implements MigrationInterface {
  name = 'AuditLog1724757388002';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "AUDIT_LOGS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "ACTION" varchar2(255) NOT NULL, "ACCOUNT_ID" number NOT NULL, "IP_ADDRESS" varchar2(255) NOT NULL, "USER_AGENT" varchar2(255), "ENTITY_ID" varchar2(255), "ENTITY_TYPE" varchar2(255), "ATTRIBUTES" clob NOT NULL, "OLD_VALUE" clob, "NEW_VALUE" clob, "ERROR_DETAILS" clob, "IV" varchar2(255) NOT NULL, "ENCRYPTED_DATA" clob, CONSTRAINT "UQ_312c7c3ebc03a19c510e887d684" UNIQUE ("UUID"), CONSTRAINT "PK_8ac929f7225df2114698217eadd" PRIMARY KEY ("ID"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "AUDIT_LOGS"`);
  }
}
