import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateJobForecastApplication1729857465399 implements MigrationInterface {
  name = 'CreateJobForecastApplication1729857465399';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "JOB_FORECAST_MATERIAL_REQUESTS"
                             (
                                 "ID"            number GENERATED BY DEFAULT AS IDENTITY,
                                 "UUID"          varchar2(36) NOT NULL,
                                 "CREATED_AT"    timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "UPDATED_AT"    timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "CODE"          varchar2(255) NOT NULL,
                                 "ACCOUNT_ID"    number                              NOT NULL,
                                 "MATERIALS"     varchar2(255) NOT NULL,
                                 "QUANTITY"      number                              NOT NULL,
                                 "VALUE"         number                              NOT NULL,
                                 "SPECIFICATION" varchar2(255) NOT NULL,
                                 "REQUEST_ID"    number,
                                 CONSTRAINT "UQ_b4095ae6488d7a5d8ef0a06a310" UNIQUE ("UUID"),
                                 CONSTRAINT "UQ_dcc372ef42cadc45c998edbae51" UNIQUE ("CODE"),
                                 CONSTRAINT "PK_38f0f0cc4737beeca1201c8f66d" PRIMARY KEY ("ID")
                             )`);
    await queryRunner.query(`CREATE TABLE "JOB_FORECAST_APPLICATIONS"
                             (
                                 "ID"                 number GENERATED BY DEFAULT AS IDENTITY,
                                 "UUID"               varchar2(36) NOT NULL,
                                 "CREATED_AT"         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "UPDATED_AT"         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "APP_NUMBER"         varchar2(255) NOT NULL,
                                 "CERTIFICATE_NUMBER" varchar2(255),
                                 "DATE_APPROVED"      timestamp,
                                 "DATE_SUBMITTED"     timestamp,
                                 "ACCOUNT_ID"         number                              NOT NULL,
                                 "STATUS"             varchar2(255) DEFAULT 'NOT_SUBMITTED' NOT NULL,
                                 "WF_CASE_ID"         varchar2(255),
                                 "PARENT_ID"          number,
                                 CONSTRAINT "UQ_b740da72b82374f730749b0b6f0" UNIQUE ("UUID"),
                                 CONSTRAINT "UQ_581796e18f642405866d1f15e96" UNIQUE ("APP_NUMBER"),
                                 CONSTRAINT "UQ_af97e831ecbc90073a7178cc155" UNIQUE ("CERTIFICATE_NUMBER"),
                                 CONSTRAINT "PK_8899bd1e80ae256f55e6ef59f53" PRIMARY KEY ("ID")
                             )`);
    await queryRunner.query(
      `CREATE INDEX "IDX_204ba454383410da4789a87cc8" ON "JOB_FORECAST_APPLICATIONS" ("APP_NUMBER", "CERTIFICATE_NUMBER")`,
    );
    await queryRunner.query(`CREATE TABLE "JOB_FORECAST_REQUESTS"
                             (
                                 "ID"                          number GENERATED BY DEFAULT AS IDENTITY,
                                 "UUID"                        varchar2(36) NOT NULL,
                                 "CREATED_AT"                  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "UPDATED_AT"                  timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 "ACCOUNT_ID"                  number                              NOT NULL,
                                 "IS_APPROVED"                 number    DEFAULT 0                 NOT NULL,
                                 "CODE"                        varchar2(255) NOT NULL,
                                 "SERVICE_REQUIRED_TYPE"       varchar2(255) NOT NULL,
                                 "TENDER_NUMBER"               varchar2(255) NOT NULL,
                                 "ESTIMATED_COST"              varchar2(255) NOT NULL,
                                 "CONTRACT_AWARD"              varchar2(255) NOT NULL,
                                 "ITT_ISSUANCE_DATE"           timestamp                           NOT NULL,
                                 "ITT_ISSUANCE_CLOSURE_DATE"   timestamp                           NOT NULL,
                                 "AWARD_DATE"                  timestamp                           NOT NULL,
                                 "PERIOD_OFF_SUBMISSION_START" timestamp                           NOT NULL,
                                 "PERIOD_OFF_SUBMISSION_END"   timestamp                           NOT NULL,
                                 "REMARKS"                     varchar2(255) NOT NULL,
                                 "APPLICATION_ID"              number,
                                 CONSTRAINT "UQ_fba6c1ebd924d9e7b416ae0f49e" UNIQUE ("UUID"),
                                 CONSTRAINT "UQ_51214870fc92abe45ceabb3f698" UNIQUE ("CODE"),
                                 CONSTRAINT "PK_4c9c98632fa6dd30110b6b052a4" PRIMARY KEY ("ID")
                             )`);
    await queryRunner.query(`CREATE TABLE "JOB_FOR_REQ_SER_REQ"
                             (
                                 "JOB_FORECAST_REQUEST_ID" number NOT NULL,
                                 "BASE_RECORD_ID"          number NOT NULL,
                                 CONSTRAINT "PK_7d03f099e5a39821b1f97163e0a" PRIMARY KEY ("JOB_FORECAST_REQUEST_ID", "BASE_RECORD_ID")
                             )`);
    await queryRunner.query(
      `CREATE INDEX "IDX_2d321b234d4a2ad82e64e3de10" ON "JOB_FOR_REQ_SER_REQ" ("JOB_FORECAST_REQUEST_ID")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_7242e4de1238cf08f430a2acad" ON "JOB_FOR_REQ_SER_REQ" ("BASE_RECORD_ID")`,
    );

    await queryRunner.query(`ALTER TABLE "JOB_FORECAST_MATERIAL_REQUESTS"
        ADD CONSTRAINT "FK_f428f2068363a63763853b89873" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "JOB_FORECAST_MATERIAL_REQUESTS"
        ADD CONSTRAINT "FK_d9c46902869691c53266a34ed6f" FOREIGN KEY ("REQUEST_ID") REFERENCES "JOB_FORECAST_REQUESTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "JOB_FORECAST_APPLICATIONS"
        ADD CONSTRAINT "FK_4951a81d45a9ec2b5b5ef1b8e22" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "JOB_FORECAST_REQUESTS"
        ADD CONSTRAINT "FK_0f709bcfada602474cdb186b802" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "JOB_FORECAST_REQUESTS"
        ADD CONSTRAINT "FK_196b48248d41e8c9866e756f6f0" FOREIGN KEY ("APPLICATION_ID") REFERENCES "JOB_FORECAST_APPLICATIONS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "JOB_FOR_REQ_SER_REQ"
        ADD CONSTRAINT "FK_2d321b234d4a2ad82e64e3de10e" FOREIGN KEY ("JOB_FORECAST_REQUEST_ID") REFERENCES "JOB_FORECAST_REQUESTS" ("ID") ON DELETE CASCADE`);
    await queryRunner.query(`ALTER TABLE "JOB_FOR_REQ_SER_REQ"
        ADD CONSTRAINT "FK_7242e4de1238cf08f430a2acad9" FOREIGN KEY ("BASE_RECORD_ID") REFERENCES "BASE_RECORDS" ("ID") ON DELETE CASCADE`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "JOB_FOR_REQ_SER_REQ" DROP CONSTRAINT "FK_7242e4de1238cf08f430a2acad9"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_FOR_REQ_SER_REQ" DROP CONSTRAINT "FK_2d321b234d4a2ad82e64e3de10e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_FORECAST_REQUESTS" DROP CONSTRAINT "FK_196b48248d41e8c9866e756f6f0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_FORECAST_REQUESTS" DROP CONSTRAINT "FK_0f709bcfada602474cdb186b802"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_FORECAST_APPLICATIONS" DROP CONSTRAINT "FK_4951a81d45a9ec2b5b5ef1b8e22"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_FORECAST_MATERIAL_REQUESTS" DROP CONSTRAINT "FK_d9c46902869691c53266a34ed6f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_FORECAST_MATERIAL_REQUESTS" DROP CONSTRAINT "FK_f428f2068363a63763853b89873"`,
    );

    await queryRunner.query(`DROP INDEX "IDX_7242e4de1238cf08f430a2acad"`);
    await queryRunner.query(`DROP INDEX "IDX_2d321b234d4a2ad82e64e3de10"`);
    await queryRunner.query(`DROP TABLE "JOB_FOR_REQ_SER_REQ"`);
    await queryRunner.query(`DROP TABLE "JOB_FORECAST_REQUESTS"`);
    await queryRunner.query(`DROP INDEX "IDX_204ba454383410da4789a87cc8"`);
    await queryRunner.query(`DROP TABLE "JOB_FORECAST_APPLICATIONS"`);
    await queryRunner.query(`DROP TABLE "JOB_FORECAST_MATERIAL_REQUESTS"`);
  }
}
