import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateMvcReportEntity1746643588274 implements MigrationInterface {
  name = 'CreateMvcReportEntity1746643588274';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "MVC_REPORT_ITEMS"
                             (
                               "ID"                                 number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"                               varchar2(36) NOT NULL,
                               "CREATED_AT"                         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"                         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "ACCOUNT_ID"                         number                              NOT NULL,
                               "CODE"                               varchar2(255) NOT NULL,
                               "APPLICATION_ID"                     number,
                               "PROJECT_NAME"                       varchar2(255) NOT NULL,
                               "TYPE_OF_SERVICE"                    varchar2(255) NOT NULL,
                               "PROJECT_LOCATION"                   varchar2(255),
                               "PROJECT_START_DATE"                 varchar2(255) NOT NULL,
                               "PROJECT_COMPLETION_DATE"            varchar2(255) NOT NULL,
                               "CONTRACT_VALUE"                     varchar2(255) NOT NULL,
                               "NC_PERCENTAGE"                      varchar2(255) NOT NULL,
                               "VESSEL_NAME"                        varchar2(255) NOT NULL,
                               "VESSEL_TYPE_ID"                     number                              NOT NULL,
                               "FLAG_ID"                            number,
                               "IMO_NUMBER"                         varchar2(255) NOT NULL,
                               "NIMASA_OWNER_REG_NO"                varchar2(255) NOT NULL,
                               "NIMASA_VESSEL_REGISTRATION_CERT_NO" varchar2(255),
                               "VESSEL_OWNERSHIP_STATUS"            varchar2(255),
                               "NUMBER_OF_NIG_PERSONNEL"            number,
                               "NUMBER_OF_EXP_PERSONNEL"            number,
                               "CONTRACTOR_NAME"                    varchar2(255),
                               "IS_APPROVED"                        number    DEFAULT 0                 NOT NULL,
                               "VESSEL_ID"                          number,
                               "OPERATOR_ID"                        number                              NOT NULL,
                               CONSTRAINT "UQ_f104b55d1c527feedbfa9f36ccb" UNIQUE ("UUID"),
                               CONSTRAINT "UQ_19feab4942f1079e5c94dfc37bb" UNIQUE ("CODE"),
                               CONSTRAINT "PK_5a06980c3948e363e57dc1522e2" PRIMARY KEY ("ID")
                             )`);
    await queryRunner.query(`CREATE TABLE "MVC_REPORTS"
                             (
                               "ID"                 number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"               varchar2(36) NOT NULL,
                               "CREATED_AT"         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"         timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "APP_NUMBER"         varchar2(255) NOT NULL,
                               "CERTIFICATE_NUMBER" varchar2(255),
                               "DATE_APPROVED"      timestamp,
                               "DATE_SUBMITTED"     timestamp,
                               "ACCOUNT_ID"         number                              NOT NULL,
                               "STATUS"             varchar2(255) DEFAULT 'NOT_SUBMITTED' NOT NULL,
                               "WF_CASE_ID"         varchar2(255),
                               "PARENT_ID"          number,
                               "FISCAL_YEAR"        varchar2(255) NOT NULL,
                               "QUARTER"            varchar2(255) NOT NULL,
                               "ADDRESS"            varchar2(255) NOT NULL,
                               "PHONE_NUMBER"       number                              NOT NULL,
                               "EMAIL"              varchar2(255) NOT NULL,
                               CONSTRAINT "UQ_f8aa669e6e4b4b6730ae5452be9" UNIQUE ("UUID"),
                               CONSTRAINT "UQ_21012c0b0f44a58016ce3627fe8" UNIQUE ("APP_NUMBER"),
                               CONSTRAINT "UQ_6551c3433a5d926bda404926a64" UNIQUE ("CERTIFICATE_NUMBER"),
                               CONSTRAINT "PK_895a6a8b6fc0b457da0adfd0b9a" PRIMARY KEY ("ID")
                             )`);
    await queryRunner.query(
      `CREATE INDEX "IDX_772f130aceeb75991c7615e9b8" ON "MVC_REPORTS" ("APP_NUMBER", "CERTIFICATE_NUMBER")`,
    );
    await queryRunner.query(`ALTER TABLE "MVC_REPORT_ITEMS"
      ADD CONSTRAINT "FK_aaadae805b53fab1df0a1908455" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "MVC_REPORT_ITEMS"
      ADD CONSTRAINT "FK_f020ec94ca269af23a506b66ca8" FOREIGN KEY ("APPLICATION_ID") REFERENCES "MVC_REPORTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "MVC_REPORT_ITEMS"
      ADD CONSTRAINT "FK_a8a0146ea7500aa93c0a4b669f4" FOREIGN KEY ("VESSEL_TYPE_ID") REFERENCES "BASE_RECORDS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "MVC_REPORT_ITEMS"
      ADD CONSTRAINT "FK_cc84fd412546509dca802596671" FOREIGN KEY ("FLAG_ID") REFERENCES "BASE_RECORDS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "MVC_REPORT_ITEMS"
      ADD CONSTRAINT "FK_261dbc6a22ed331d180c20d11d2" FOREIGN KEY ("VESSEL_ID") REFERENCES "MARINE_VESSEL_APPLICATIONS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "MVC_REPORT_ITEMS"
      ADD CONSTRAINT "FK_94ca2b4613e81549390220b9066" FOREIGN KEY ("OPERATOR_ID") REFERENCES "ACCOUNTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "MVC_REPORTS"
      ADD CONSTRAINT "FK_e57c6a5049d76133ddf7cddb8e6" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "MVC_REPORTS" DROP CONSTRAINT "FK_e57c6a5049d76133ddf7cddb8e6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "MVC_REPORT_ITEMS" DROP CONSTRAINT "FK_94ca2b4613e81549390220b9066"`,
    );
    await queryRunner.query(
      `ALTER TABLE "MVC_REPORT_ITEMS" DROP CONSTRAINT "FK_261dbc6a22ed331d180c20d11d2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "MVC_REPORT_ITEMS" DROP CONSTRAINT "FK_cc84fd412546509dca802596671"`,
    );
    await queryRunner.query(
      `ALTER TABLE "MVC_REPORT_ITEMS" DROP CONSTRAINT "FK_a8a0146ea7500aa93c0a4b669f4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "MVC_REPORT_ITEMS" DROP CONSTRAINT "FK_f020ec94ca269af23a506b66ca8"`,
    );
    await queryRunner.query(
      `ALTER TABLE "MVC_REPORT_ITEMS" DROP CONSTRAINT "FK_aaadae805b53fab1df0a1908455"`,
    );
    await queryRunner.query(`DROP TABLE "MVC_REPORTS"`);
    await queryRunner.query(`DROP TABLE "MVC_REPORT_ITEMS"`);
  }
}
