import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateResearchApplicationEntity1750718687013 implements MigrationInterface {
  name = 'CreateResearchApplicationEntity1750718687013';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "RESEARCH_RESEARCHERS"
                             (
                               "ID"                        number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"                      varchar2(36) NOT NULL,
                               "CREATED_AT"                timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"                timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "GENDER"                    varchar2(255) NOT NULL,
                               "DATE_OF_BIRTH"             timestamp                           NOT NULL,
                               "EMAIL"                     varchar2(255) NOT NULL,
                               "AREA_OF_SPECIALIZATION_ID" number,
                               "ORGANIZATION_NAME"         varchar2(255) NOT NULL,
                               "FACULTY_ID"                number                              NOT NULL,
                               "NAME"                      varchar2(255) NOT NULL,
                               "POSITION_ID"               number,
                               "RANK"                      varchar2(255),
                               "POSTAL_ADDRESS"            varchar2(255) NOT NULL,
                               "TELEPHONE"                 varchar2(255),
                               "CATEGORY"                  varchar2(255) NOT NULL,
                               "CITY"                      varchar2(255),
                               "APPLICATION_ID"            number,
                               CONSTRAINT "UQ_821b2160528580e83770288efea" UNIQUE ("UUID"),
                               CONSTRAINT "PK_549d0090a6d849cee636e767454" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(`CREATE TABLE "RESEARCH_MATRICES"
                             (
                               "ID"         number GENERATED BY DEFAULT AS IDENTITY,
                               "NAME"       varchar2(255) NOT NULL,
                               "TOTAL_MARK" number NOT NULL,
                               "TYPE"       varchar2(255) NOT NULL,
                               CONSTRAINT "PK_f72bf3fd650ef7e71c196c63cb6" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(`CREATE TABLE "RESEARCH_EVALUATIONS"
                             (
                               "ID"             number GENERATED BY DEFAULT AS IDENTITY,
                               "SCORE"          float,
                               "REMARKS"        clob,
                               "CREATED_AT"     timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"     timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "APPLICATION_ID" number,
                               "MATRIX_ID"      number,
                               CONSTRAINT "PK_a94fcf572dfd0c54dacfa81d015" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(`CREATE TABLE "RESEARCH"
                             (
                               "ID"                            number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"                          varchar2(36) NOT NULL,
                               "CREATED_AT"                    timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"                    timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "APP_NUMBER"                    varchar2(255) NOT NULL,
                               "CERTIFICATE_NUMBER"            varchar2(255),
                               "DATE_APPROVED"                 timestamp,
                               "DATE_SUBMITTED"                timestamp,
                               "ACCOUNT_ID"                    number                              NOT NULL,
                               "STATUS"                        varchar2(255) DEFAULT 'NOT_SUBMITTED' NOT NULL,
                               "WF_CASE_ID"                    varchar2(255),
                               "PARENT_ID"                     number,
                               "IS_APPROVED"                   number    DEFAULT 0                 NOT NULL,
                               "GRANT_TYPE"                    varchar2(255) NOT NULL,
                               "THEMATIC_AREA_ID"              number,
                               "RESEARCH_TITLE"                varchar2(255),
                               "CENTER_OF_EXCELLENCE_ID"       number,
                               "INTRODUCTION"                  clob,
                               "OBJECTIVE"                     clob,
                               "EXPECTED_RESULT"               clob,
                               "INNOVATION"                    clob,
                               "TEAM_BACKGROUND"               clob,
                               "CUT_OFF_MARK"                  float     DEFAULT 70                NOT NULL,
                               "CONCEPTUAL_BACKGROUND"         clob,
                               "GOAL_AND_OBJECTIVES"           clob,
                               "COMPANY_NAME"                  varchar2(255),
                               "TITLE_OF_INNOVATION"           varchar2(255),
                               "PROPOSED_RESEARCH_TITLE"       varchar2(255),
                               "DESCRIPTION_OF_INNOVATION"     clob,
                               "STARTUP_VISION_MISSION_VALUES" clob,
                               "STARTUP_OBJECTIVES"            clob,
                               "STARTUP_TEAM_STRUCTURE"        clob,
                               "STARTUP_FUNDING_MODEL"         clob,
                               "MARKETING_PLAN"                clob,
                               "RISK_ANALYSIS"                 clob,
                               "BUDGET_ESTIMATE"               clob,
                               "PROBLEM_STATEMENT"             varchar2(255),
                               "SOLUTIONS"                     varchar2(255),
                               "IS_PATENT"                     varchar2(255),
                               "IS_MEETING_SCHEDULED"          number    DEFAULT 0                 NOT NULL,
                               "MEET_DATE"                     timestamp,
                               "MEET_LINK"                     varchar2(255),
                               "IS_MEETING_CONDUCTED"          number    DEFAULT 0                 NOT NULL,
                               CONSTRAINT "UQ_8c0083ce03e4fb7db2cfcd85f59" UNIQUE ("UUID"),
                               CONSTRAINT "UQ_2d13a5ca107073e3014d0653818" UNIQUE ("APP_NUMBER"),
                               CONSTRAINT "UQ_54c3690852564e6c7fc32d1977f" UNIQUE ("CERTIFICATE_NUMBER"),
                               CONSTRAINT "PK_0ace12a6ff0e4d5efd06bd1c963" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(
      `CREATE INDEX "IDX_5c9a8d0a9fb320be16a3189832" ON "RESEARCH" ("APP_NUMBER", "CERTIFICATE_NUMBER")`,
    );

    await queryRunner.query(`CREATE TABLE "RESEARCH_FOCUS_AREA"
                             (
                               "RESEARCH_ID"    number NOT NULL,
                               "BASE_RECORD_ID" number NOT NULL,
                               CONSTRAINT "PK_3e533142a65fb551d33356b76f7" PRIMARY KEY ("RESEARCH_ID", "BASE_RECORD_ID")
                             )`);

    await queryRunner.query(
      `CREATE INDEX "IDX_5aaed6692d393f0573586272ec" ON "RESEARCH_FOCUS_AREA" ("RESEARCH_ID")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_a041797c68707545c6040ca472" ON "RESEARCH_FOCUS_AREA" ("BASE_RECORD_ID")`,
    );

    // Foreign Keys
    await queryRunner.query(`ALTER TABLE "RESEARCH_RESEARCHERS"
      ADD CONSTRAINT "FK_c49f3da3d417a8cdc0a2586304a" FOREIGN KEY ("AREA_OF_SPECIALIZATION_ID") REFERENCES "BASE_RECORDS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "RESEARCH_RESEARCHERS"
      ADD CONSTRAINT "FK_dd84610376015ef0536be5956da" FOREIGN KEY ("FACULTY_ID") REFERENCES "BASE_RECORDS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "RESEARCH_RESEARCHERS"
      ADD CONSTRAINT "FK_50caf5d8d61b87c33e890e266bd" FOREIGN KEY ("POSITION_ID") REFERENCES "BASE_RECORDS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "RESEARCH_RESEARCHERS"
      ADD CONSTRAINT "FK_ddc53c96db8f847f217eacda823" FOREIGN KEY ("APPLICATION_ID") REFERENCES "RESEARCH" ("ID")`);

    await queryRunner.query(`ALTER TABLE "RESEARCH_EVALUATIONS"
      ADD CONSTRAINT "FK_15ef04d2fc8211f1efbaa8a0f68" FOREIGN KEY ("APPLICATION_ID") REFERENCES "RESEARCH" ("ID") ON DELETE CASCADE`);
    await queryRunner.query(`ALTER TABLE "RESEARCH_EVALUATIONS"
      ADD CONSTRAINT "FK_f38549f731d09e97b149e1942cc" FOREIGN KEY ("MATRIX_ID") REFERENCES "RESEARCH_MATRICES" ("ID") ON DELETE CASCADE`);

    await queryRunner.query(`ALTER TABLE "RESEARCH"
      ADD CONSTRAINT "FK_5e87c465e89e5bd69bcde89f5c1" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "RESEARCH"
      ADD CONSTRAINT "FK_6675547f1f08285c8ec3a142d60" FOREIGN KEY ("THEMATIC_AREA_ID") REFERENCES "BASE_RECORDS" ("ID")`);
    await queryRunner.query(`ALTER TABLE "RESEARCH"
      ADD CONSTRAINT "FK_2f10ec9f2e7291ab7e2675795d2" FOREIGN KEY ("CENTER_OF_EXCELLENCE_ID") REFERENCES "BASE_RECORDS" ("ID")`);

    await queryRunner.query(`ALTER TABLE "RESEARCH_FOCUS_AREA"
      ADD CONSTRAINT "FK_5aaed6692d393f0573586272ec7" FOREIGN KEY ("RESEARCH_ID") REFERENCES "RESEARCH" ("ID") ON DELETE CASCADE`);
    await queryRunner.query(`ALTER TABLE "RESEARCH_FOCUS_AREA"
      ADD CONSTRAINT "FK_a041797c68707545c6040ca4723" FOREIGN KEY ("BASE_RECORD_ID") REFERENCES "BASE_RECORDS" ("ID") ON DELETE CASCADE`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_FOCUS_AREA" DROP CONSTRAINT "FK_a041797c68707545c6040ca4723"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_FOCUS_AREA" DROP CONSTRAINT "FK_5aaed6692d393f0573586272ec7"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH" DROP CONSTRAINT "FK_2f10ec9f2e7291ab7e2675795d2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH" DROP CONSTRAINT "FK_6675547f1f08285c8ec3a142d60"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH" DROP CONSTRAINT "FK_5e87c465e89e5bd69bcde89f5c1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_EVALUATIONS" DROP CONSTRAINT "FK_f38549f731d09e97b149e1942cc"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_EVALUATIONS" DROP CONSTRAINT "FK_15ef04d2fc8211f1efbaa8a0f68"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_RESEARCHERS" DROP CONSTRAINT "FK_ddc53c96db8f847f217eacda823"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_RESEARCHERS" DROP CONSTRAINT "FK_50caf5d8d61b87c33e890e266bd"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_RESEARCHERS" DROP CONSTRAINT "FK_dd84610376015ef0536be5956da"`,
    );
    await queryRunner.query(
      `ALTER TABLE "RESEARCH_RESEARCHERS" DROP CONSTRAINT "FK_c49f3da3d417a8cdc0a2586304a"`,
    );

    await queryRunner.query(`DROP INDEX "IDX_a041797c68707545c6040ca472"`);
    await queryRunner.query(`DROP INDEX "IDX_5aaed6692d393f0573586272ec"`);
    await queryRunner.query(`DROP TABLE "RESEARCH_FOCUS_AREA"`);
    await queryRunner.query(`DROP INDEX "IDX_5c9a8d0a9fb320be16a3189832"`);
    await queryRunner.query(`DROP TABLE "RESEARCH"`);
    await queryRunner.query(`DROP TABLE "RESEARCH_EVALUATIONS"`);
    await queryRunner.query(`DROP TABLE "RESEARCH_MATRICES"`);
    await queryRunner.query(`DROP TABLE "RESEARCH_RESEARCHERS"`);
  }
}
