import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateServiceUtilizationApplication1751534127024 implements MigrationInterface {
  name = 'CreateServiceUtilizationApplication1751534127024';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "SERVICE_UTILIZATION_APPLICATIONS"
                             (
                               "ID"                  number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"                varchar2(36) NOT NULL,
                               "CREATED_AT"          timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"          timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "APP_NUMBER"          varchar2(255) NOT NULL,
                               "CERTIFICATE_NUMBER"  varchar2(255),
                               "DATE_APPROVED"       timestamp,
                               "DATE_SUBMITTED"      timestamp,
                               "ACCOUNT_ID"          number                              NOT NULL,
                               "STATUS"              varchar2(255) DEFAULT 'NOT_SUBMITTED' NOT NULL,
                               "WF_CASE_ID"          varchar2(255),
                               "PARENT_ID"           number,
                               "REPORT_TYPE"         varchar2(255) NOT NULL,
                               "REPORTING_PERIOD"    varchar2(255),
                               "REPORTING_YEAR"      varchar2(255),
                               "REPORT_STATUS"       varchar2(255) DEFAULT 'SCHEDULED' NOT NULL,
                               "CATEGORY_ID"         number,
                               "TYPE_ID"             number,
                               "SUPPORTING_COMMENT"  clob,
                               "SIGNATORY_NAME"      varchar2(255),
                               "SIGNATURE"           number,
                               "DESIGNATION_ID"      number,
                               "PERCENTAGE_RETAINED" varchar2(255),
                               CONSTRAINT "UQ_8d8342b86ff227589971031e8ac" UNIQUE ("UUID"),
                               CONSTRAINT "UQ_560ffe8db4677c72c9e19ba4cb7" UNIQUE ("APP_NUMBER"),
                               CONSTRAINT "UQ_697a16f0473985df56b4503637a" UNIQUE ("CERTIFICATE_NUMBER"),
                               CONSTRAINT "PK_61d3ca4c79f54860bd4dd9002e3" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(`CREATE TABLE "SERVICE_UTILIZATION_REV_RETENTIONS"
                             (
                               "ID"                           number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"                         varchar2(36) NOT NULL,
                               "CREATED_AT"                   timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"                   timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "ACCOUNT_ID"                   number                              NOT NULL,
                               "UNIQUE_KEY"                   varchar2(255) NOT NULL,
                               "CODE"                         varchar2(255) NOT NULL,
                               "INSTITUTION_CLASSIFICATION"   varchar2(255) NOT NULL,
                               "INSTITUTION_NAME"             varchar2(255) NOT NULL,
                               "INSTITUTION_ADDRESS"          clob                                NOT NULL,
                               "PERCENTAGE_RETAINED"          varchar2(255),
                               "TOTAL_NIG_OPERATION"          number(20,2),
                               "TRANSACTION_CURRENCY"         varchar2(255),
                               "REMARKS"                      varchar2(255),
                               "VALUE_OF_TRANSACTION"         number(20,2),
                               "TOTAL_SPENT"                  number(20,2),
                               "TOTAL_FEE_PAID"               number(20,2),
                               "CURRENCY_OF_PREMIUM_PAID"     varchar2(255),
                               "PREMIUM_PAID"                 number(20,2),
                               "CURRENCY_OF_SUM_ASSURED"      varchar2(255),
                               "SUM_ASSURED"                  number(20,2),
                               "BROKER_NAME"                  varchar2(255),
                               "BROKER_ADDRESS"               varchar2(255),
                               "TRANSACTION_AMOUNT"           number(20,2),
                               "PREMIUM_PAID_TO_NIG"          number(20,2),
                               "DESCRIPTION_OF_LEGAL_SERVICE" varchar2(255),
                               "PRINCIPAL_NAME"               varchar2(255),
                               "REPORTING_PERIOD"             varchar2(255),
                               "REPORTING_YEAR"               varchar2(255),
                               "APPLICATION_ID"               number,
                               CONSTRAINT "UQ_dc9d9f440839f1a2abb1258b48e" UNIQUE ("UUID"),
                               CONSTRAINT "UQ_f9fcb981077b0064fd4a2ae837c" UNIQUE ("CODE"),
                               CONSTRAINT "PK_cbe035257faae941936413b81ce" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(`CREATE TABLE "SERVICE_UTILIZATION_RETENTIONS_CLOSING_BALANCES"
                             (
                               "ID"                   number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"                 varchar2(36) NOT NULL,
                               "CREATED_AT"           timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"           timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "INSTITUTION_NAME"     varchar2(255) NOT NULL,
                               "CLOSING_BALANCE"      varchar2(255),
                               "CURRENCY"             varchar2(255),
                               "APPLICATION_ID"       number,
                               "REVENUE_RETENTION_ID" number,
                               CONSTRAINT "UQ_cd192d45cf179eb6e97064263c3" UNIQUE ("UUID"),
                               CONSTRAINT "PK_3c9baf4d2ccf7915cf014d73529" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(`CREATE TABLE "SERVICE_UTILIZATIONS_REPORTS"
                             (
                               "ID"                               number GENERATED BY DEFAULT AS IDENTITY,
                               "UUID"                             varchar2(36) NOT NULL,
                               "CREATED_AT"                       timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "UPDATED_AT"                       timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "CODE"                             varchar2(255) NOT NULL,
                               "CATEGORY_ID"                      number,
                               "TYPE_ID"                          number,
                               "OTHERS_TYPE"                      varchar2(255),
                               "APPLICATION_ID"                   number,
                               "REVENUE_RETENTION_ID"             number,
                               "UNIQUE_KEY"                       varchar2(255) NOT NULL,
                               "REPORT_TYPE"                      varchar2(255) NOT NULL,
                               "IS_APPROVED"                      number    DEFAULT 0                 NOT NULL,
                               "ACCOUNT_ID"                       number                              NOT NULL,
                               "INSTITUTION_CLASSIFICATION"       varchar2(255) NOT NULL,
                               "CURRENCY_OF_PREMIUM_PAID"         varchar2(255),
                               "PREMIUM_PAID"                     varchar2(255),
                               "CURRENCY_OF_SUM_ASSURED"          varchar2(255),
                               "SUM_ASSURED"                      number,
                               "BROKER_NAME"                      varchar2(255),
                               "BROKER_ADDRESS"                   varchar2(255),
                               "TRANSACTION_AMOUNT"               number,
                               "PREMIUM_PAID_TO_NIG"              varchar2(255),
                               "INSTITUTION_NAME"                 varchar2(255),
                               "INSTITUTION_ADDRESS"              clob,
                               "REPORTING_PERIOD"                 varchar2(255),
                               "REPORTING_YEAR"                   varchar2(255),
                               "TRANSACTION_CURRENCY"             varchar2(255),
                               "OTHER_EXPENSES_CURRENCY"          varchar2(255),
                               "VALUE_OF_TRANSACTION"             varchar2(255),
                               "TOTAL_SPENT"                      number,
                               "TOTAL_FEE_PAID"                   number,
                               "DESCRIPTION_OF_LEGAL_SERVICE"     varchar2(255),
                               "PRINCIPAL_NAME"                   varchar2(255),
                               "ASSET_DESCRIPTION"                varchar2(255),
                               "LEAD_INSURANCE_COMPANY"           varchar2(255),
                               "INSURANCE_COMPANY_ADDRESS"        varchar2(255),
                               "INSURANCE_COMPANY_CLASSIFICATION" varchar2(255),
                               "COVER_NAME"                       varchar2(255),
                               "INSURANCE_CLASS"                  varchar2(255),
                               "POLICY_NUMBER"                    varchar2(255),
                               "INSURANCE_PERIOD"                 varchar2(255),
                               "PARTNERSHIP_NATURE"               varchar2(255),
                               "ASSET_VALUE"                      number,
                               "INTEREST_PERCENTAGE"              number,
                               "SUM_INSURED_CURRENCY"             varchar2(255),
                               "ASSET_VALUE_CURRENCY"             varchar2(255),
                               "SUM_INSURED_AMOUNT"               number,
                               "SUM_ASSURED_BASIS"                varchar2(255),
                               "PREMIUM_CURRENCY"                 varchar2(255),
                               "PREMIUM_AMOUNT"                   number,
                               "LEAD_BROKER_NAME"                 varchar2(255),
                               "BROKER_FEE_CURRENCY"              varchar2(255),
                               "BROKER_FEE_PAID"                  number,
                               "OTHER_EXPENSES"                   number,
                               "UNDERWRITER_LIST"                 clob,
                               "BROKER_LIST"                      clob,
                               "PREMIUM_BUDGET_AMOUNT"            number,
                               "PREMIUM_BUDGET_CURRENCY"          varchar2(255),
                               "REMARKS"                          varchar2(255),
                               CONSTRAINT "UQ_f6ccefe5543b1c14304500031fb" UNIQUE ("UUID"),
                               CONSTRAINT "UQ_eebeac703461e41f55b72b3b1e0" UNIQUE ("CODE"),
                               CONSTRAINT "PK_598b378f359726778764c333c83" PRIMARY KEY ("ID")
                             )`);

    await queryRunner.query(
      `CREATE INDEX "IDX_551811eec00b6b2607478cacaa" ON "SERVICE_UTILIZATION_APPLICATIONS" ("APP_NUMBER", "CERTIFICATE_NUMBER")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "SERVICE_UTILIZATION_REV_RETENTIONS"`);
    await queryRunner.query(
      `DROP TABLE "SERVICE_UTILIZATION_RETENTIONS_CLOSING_BALANCES"`,
    );
    await queryRunner.query(`DROP INDEX "IDX_551811eec00b6b2607478cacaa"`);
    await queryRunner.query(`DROP TABLE "SERVICE_UTILIZATION_APPLICATIONS"`);
    await queryRunner.query(`DROP TABLE "SERVICE_UTILIZATIONS_REPORTS"`);
  }
}
