import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddAdditionalFieldsToServiceUtilizationReport1752933881556 implements MigrationInterface {
  name = 'AddAdditionalFieldsToServiceUtilizationReport1752933881556';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" ADD "SPEND_AMOUNT_CURRENCY" varchar2(255)`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" ADD "SPEND_AMOUNT" number`,
    );

    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_REV_RETENTIONS" ADD CONSTRAINT "FK_cccfcf8f7d0fa1b42ca3f3c50c7" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_REV_RETENTIONS" ADD CONSTRAINT "FK_6e8cb6c34e02440bb81ad58a0b6" FOREIGN KEY ("APPLICATION_ID") REFERENCES "SERVICE_UTILIZATION_APPLICATIONS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_RETENTIONS_CLOSING_BALANCES" ADD CONSTRAINT "FK_a5edd7225449cdd76e0b48ce1ca" FOREIGN KEY ("APPLICATION_ID") REFERENCES "SERVICE_UTILIZATION_APPLICATIONS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_RETENTIONS_CLOSING_BALANCES" ADD CONSTRAINT "FK_ccfd9fe3853e073e72cd9785ee1" FOREIGN KEY ("REVENUE_RETENTION_ID") REFERENCES "SERVICE_UTILIZATION_REV_RETENTIONS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" ADD CONSTRAINT "FK_3f37ad6ca6cefc81462295da93f" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" ADD CONSTRAINT "FK_c482b137fbf2d33eb9aef8d7eac" FOREIGN KEY ("CATEGORY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" ADD CONSTRAINT "FK_542f001d8c0f9bbe34fb7b2691d" FOREIGN KEY ("TYPE_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" ADD CONSTRAINT "FK_7325d765af3c618c46f31b1c881" FOREIGN KEY ("DESIGNATION_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" ADD CONSTRAINT "FK_e7c2b3c9cf4ce00d8cb50af0ac8" FOREIGN KEY ("CATEGORY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" ADD CONSTRAINT "FK_e60a6e21f965fb9d2523d2fac9a" FOREIGN KEY ("TYPE_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" ADD CONSTRAINT "FK_18e2176e116610f9cd16a46cd9f" FOREIGN KEY ("APPLICATION_ID") REFERENCES "SERVICE_UTILIZATION_APPLICATIONS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" ADD CONSTRAINT "FK_37ee133bb4fee09ed6180b65358" FOREIGN KEY ("REVENUE_RETENTION_ID") REFERENCES "SERVICE_UTILIZATION_REV_RETENTIONS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" ADD CONSTRAINT "FK_000c1d0c7be4f833535549bafe2" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" DROP CONSTRAINT "FK_000c1d0c7be4f833535549bafe2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" DROP CONSTRAINT "FK_37ee133bb4fee09ed6180b65358"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" DROP CONSTRAINT "FK_18e2176e116610f9cd16a46cd9f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" DROP CONSTRAINT "FK_e60a6e21f965fb9d2523d2fac9a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" DROP CONSTRAINT "FK_e7c2b3c9cf4ce00d8cb50af0ac8"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" DROP CONSTRAINT "FK_7325d765af3c618c46f31b1c881"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" DROP CONSTRAINT "FK_542f001d8c0f9bbe34fb7b2691d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" DROP CONSTRAINT "FK_c482b137fbf2d33eb9aef8d7eac"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_APPLICATIONS" DROP CONSTRAINT "FK_3f37ad6ca6cefc81462295da93f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_RETENTIONS_CLOSING_BALANCES" DROP CONSTRAINT "FK_ccfd9fe3853e073e72cd9785ee1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_RETENTIONS_CLOSING_BALANCES" DROP CONSTRAINT "FK_a5edd7225449cdd76e0b48ce1ca"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_REV_RETENTIONS" DROP CONSTRAINT "FK_6e8cb6c34e02440bb81ad58a0b6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATION_REV_RETENTIONS" DROP CONSTRAINT "FK_cccfcf8f7d0fa1b42ca3f3c50c7"`,
    );

    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" DROP COLUMN "SPEND_AMOUNT"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_UTILIZATIONS_REPORTS" DROP COLUMN "SPEND_AMOUNT_CURRENCY"`,
    );
  }
}
