/* eslint-disable prettier/prettier */
import { MigrationInterface, QueryRunner } from "typeorm";

export class UserSettings1766398044091 implements MigrationInterface {
    name = 'UserSettings1766398044091'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "USER_SETTINGS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "KEY" varchar2(255) NOT NULL, "VALUE" clob NOT NULL, "USER_ID" number, CONSTRAINT "UQ_a5575200f9614f5d46ca547c8bb" UNIQUE ("UUID"), CONSTRAINT "UQ_08203cd4fd19311b124c3e6683f" UNIQUE ("USER_ID", "KEY"), CONSTRAINT "PK_0d457c24393072928bb6984f9f7" PRIMARY KEY ("ID"))`);
        
        await queryRunner.query(`ALTER TABLE "USER_SETTINGS" ADD CONSTRAINT "FK_2260f547d9b171855dd57364e24" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "USER_SETTINGS" DROP CONSTRAINT "FK_2260f547d9b171855dd57364e24"`);
       
        await queryRunner.query(`DROP TABLE "USER_SETTINGS"`);
    }

}
