import { MigrationInterface, QueryRunner } from 'typeorm';

export class UpdateServiceCodesTable1772020224468
  implements MigrationInterface
{
  name = 'UpdateServiceCodesTable1772020224468';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "SERVICE_CODE_PAYMENTS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "ACCOUNT_ID" number NOT NULL, "STATUS" varchar2(255) DEFAULT 'UNPAID' NOT NULL, "RRR_NO" varchar2(255), "REFERENCE_NO" varchar2(255), "AMOUNT" number(20,2) NOT NULL, "METADATA" clob, "PAYMENT_DATE" timestamp, CONSTRAINT "UQ_fa2b58329f9fb13c3e016be7b96" UNIQUE ("UUID"), CONSTRAINT "UQ_329b37e22dd79da91a150dbbec2" UNIQUE ("RRR_NO"), CONSTRAINT "PK_b2ae64d91810e368a3f1ffdc037" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "COMPANY_SERVICE_CODES" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "REQ_NO" varchar2(255) NOT NULL, "ACCOUNT_ID" number NOT NULL, "APPLICATION_ID" number, "SERVICE_CODE_ID" number NOT NULL, "PAYMENT_ID" number, "IS_APPROVED" number DEFAULT 0 NOT NULL, CONSTRAINT "UQ_f1c52728f233029ecc448035294" UNIQUE ("UUID"), CONSTRAINT "UQ_289fd183a4d99f7a6b36677705b" UNIQUE ("REQ_NO"), CONSTRAINT "PK_1c2ace7bbdafd563b4b15a2382b" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "SETTINGS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "KEY" varchar2(255) NOT NULL, "VALUE" clob NOT NULL, CONSTRAINT "UQ_6b9e79dbb2a30177f16773d43e7" UNIQUE ("UUID"), CONSTRAINT "UQ_3ab01f06a20107610a9fb1ece2e" UNIQUE ("KEY"), CONSTRAINT "PK_2dcd4dd09e1260b96963827c8f2" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" DROP COLUMN "NUMBER"`);
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" DROP COLUMN "PRICE"`);
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" DROP COLUMN "LICENCE"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD "SLUG" varchar2(255) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD CONSTRAINT "UQ_80ec9c25bd5a56a9e5b64adc3b5" UNIQUE ("SLUG")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODE_APPLICATIONS" MODIFY "STATUS" varchar2(255) DEFAULT 'PENDING' `,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" DROP CONSTRAINT "UQ_eeca80509c8c2c8996df02f0308"`,
    );
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" DROP COLUMN "CODE"`);
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD "CODE" varchar2(24) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD CONSTRAINT "UQ_eeca80509c8c2c8996df02f0308" UNIQUE ("CODE")`,
    );
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" DROP COLUMN "NAME"`);
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD "NAME" varchar2(500) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_APPLICATIONS" MODIFY "STATUS" varchar2(255) DEFAULT 'PENDING' `,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_STAGE_APPS" MODIFY "STATUS" varchar2(255) DEFAULT 'PENDING' `,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_STAGE_APPLICATION_NIGERIA_CONTENT_COMPLIANCES" MODIFY "STATUS" varchar2(255) DEFAULT 'PENDING' `,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_STAGE_APPLICATION_COMMERCIAL_INVITATIONS" MODIFY "STATUS" varchar2(255) DEFAULT 'PENDING' `,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODE_PAYMENTS" ADD CONSTRAINT "FK_c36b940c14d291b27308400e712" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" ADD CONSTRAINT "FK_7c0de2a7bb293a71120b20de81f" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" ADD CONSTRAINT "FK_5906ae407eb9e77bf62c13031b5" FOREIGN KEY ("SERVICE_CODE_ID") REFERENCES "SERVICE_CODES" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" ADD CONSTRAINT "FK_f4bf5616d3afa63fbce889fd696" FOREIGN KEY ("APPLICATION_ID") REFERENCES "SERVICE_CODE_APPLICATIONS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" ADD CONSTRAINT "FK_047a7ea01aa1f960dd6551f74d2" FOREIGN KEY ("PAYMENT_ID") REFERENCES "SERVICE_CODE_PAYMENTS" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" DROP CONSTRAINT "FK_047a7ea01aa1f960dd6551f74d2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" DROP CONSTRAINT "FK_f4bf5616d3afa63fbce889fd696"`,
    );
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" DROP CONSTRAINT "FK_5906ae407eb9e77bf62c13031b5"`,
    );
    await queryRunner.query(
      `ALTER TABLE "COMPANY_SERVICE_CODES" DROP CONSTRAINT "FK_7c0de2a7bb293a71120b20de81f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODE_PAYMENTS" DROP CONSTRAINT "FK_c36b940c14d291b27308400e712"`,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_STAGE_APPLICATION_COMMERCIAL_INVITATIONS" MODIFY "STATUS" varchar2(255) DEFAULT 'NOT_SUBMITTED' `,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_STAGE_APPLICATION_NIGERIA_CONTENT_COMPLIANCES" MODIFY "STATUS" varchar2(255) DEFAULT 'NOT_SUBMITTED' `,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_STAGE_APPS" MODIFY "STATUS" varchar2(255) DEFAULT 'NOT_SUBMITTED' `,
    );
    await queryRunner.query(
      `ALTER TABLE "TENDER_APPLICATIONS" MODIFY "STATUS" varchar2(255) DEFAULT 'NOT_SUBMITTED' `,
    );
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" DROP COLUMN "NAME"`);
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD "NAME" varchar2(255) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" DROP CONSTRAINT "UQ_eeca80509c8c2c8996df02f0308"`,
    );
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" DROP COLUMN "CODE"`);
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD "CODE" varchar2(255) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD CONSTRAINT "UQ_eeca80509c8c2c8996df02f0308" UNIQUE ("CODE")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODE_APPLICATIONS" MODIFY "STATUS" varchar2(255) DEFAULT 'NOT_SUBMITTED' `,
    );
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" DROP CONSTRAINT "UQ_80ec9c25bd5a56a9e5b64adc3b5"`,
    );
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" DROP COLUMN "SLUG"`);
    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD "LICENCE" varchar2(255)`,
    );
    await queryRunner.query(`ALTER TABLE "SERVICE_CODES" ADD "PRICE" number`);

    await queryRunner.query(
      `ALTER TABLE "SERVICE_CODES" ADD "NUMBER" varchar2(255)`,
    );
    await queryRunner.query(`DROP TABLE "SETTINGS"`);
    await queryRunner.query(`DROP TABLE "COMPANY_SERVICE_CODES"`);
    await queryRunner.query(`DROP TABLE "SERVICE_CODE_PAYMENTS"`);
  }
}
