import { MigrationInterface, QueryRunner } from 'typeorm';

export class AgencyDepartment1774451779309 implements MigrationInterface {
  name = 'AgencyDepartment1774451779309';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "DEPARTMENTS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "NAME" varchar2(500) NOT NULL, "DESCRIPTION" varchar2(255), "TYPE" varchar2(255) NOT NULL, "PARENT_ID" number, CONSTRAINT "UQ_149bf718e77a9e390e3c10dd044" UNIQUE ("UUID"), CONSTRAINT "PK_a54be1a71b0622c9110b8c0c3c6" PRIMARY KEY ("ID"))`,
    );

    await queryRunner.query(
      `ALTER TABLE "ACCOUNT_AGENCY" ADD "DEPARTMENT_ID" number`,
    );
    await queryRunner.query(
      `ALTER TABLE "DEPARTMENTS" ADD CONSTRAINT "FK_4adccdb740c35126305b8a968c3" FOREIGN KEY ("PARENT_ID") REFERENCES "DEPARTMENTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACCOUNT_AGENCY" ADD CONSTRAINT "FK_a83d9d2220f539354490a88b518" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENTS" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "ACCOUNT_AGENCY" DROP CONSTRAINT "FK_a83d9d2220f539354490a88b518"`,
    );
    await queryRunner.query(
      `ALTER TABLE "DEPARTMENTS" DROP CONSTRAINT "FK_4adccdb740c35126305b8a968c3"`,
    );

    await queryRunner.query(
      `ALTER TABLE "ACCOUNT_AGENCY" DROP COLUMN "DEPARTMENT_ID"`,
    );

    await queryRunner.query(`DROP TABLE "DEPARTMENTS"`);
  }
}
