import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateSkillTrainingJobExperienceCertAcadEntity1776608536736 implements MigrationInterface {
  name = 'CreateSkillTrainingJobExperienceCertAcadEntity1776608536736';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "TRAININGS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "ACCOUNT_ID" number NOT NULL, "NAME" varchar2(255) NOT NULL, "ORG_NAME" varchar2(255) NOT NULL, "COUNTRY_ID" number NOT NULL, "DURATION" number NOT NULL, "YEAR" number NOT NULL, "DESCRIPTION" clob, CONSTRAINT "UQ_1550683327d01868f4b6e658cae" UNIQUE ("UUID"), CONSTRAINT "PK_db4a8048b4f28aa9ab373b9a535" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "SKILLS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "ACCOUNT_ID" number NOT NULL, "CATEGORY_ID" number NOT NULL, "LEVEL_ID" number NOT NULL, "YEAR" number NOT NULL, "DESCRIPTION" clob, "STATUS" number, CONSTRAINT "UQ_8e68c387249ace923a7bfc6a401" UNIQUE ("UUID"), CONSTRAINT "PK_31e5e534cc587dc6d856fc4a474" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "JOB_EXPERIENCES" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "ACCOUNT_ID" number NOT NULL, "ORG_ADDRESS" clob, "JOB_FAMILY_ID" number NOT NULL, "JOB_TYPE_ID" number NOT NULL, "START_DATE" timestamp, "END_DATE" timestamp, "DESCRIPTION" clob, "COUNTRY_ID" number NOT NULL, "ORG_NAME" varchar2(255), CONSTRAINT "UQ_c9437a973007fa6bae1595c75fb" UNIQUE ("UUID"), CONSTRAINT "PK_56168f118ee063fff2915cbd544" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "CERTIFICATIONS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "NAME" varchar2(255) NOT NULL, "ACCOUNT_ID" number NOT NULL, "CATEGORY_ID" number NOT NULL, "TYPE_ID" number NOT NULL, "CERTIFICATE_NO" varchar2(255) NOT NULL, "YEAR" number NOT NULL, "EXPIRY_YEAR" number, CONSTRAINT "UQ_586adf34c05a68bc0227a43bf6e" UNIQUE ("UUID"), CONSTRAINT "PK_af56f7b006e6096445174c395bb" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "ACADEMICS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "UUID" varchar2(36) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "ACCOUNT_ID" number NOT NULL, "COUNTRY_ID" number NOT NULL, "LEVEL_ID" number, "DISCIPLINE_ID" number, "COURSE_ID" number, "INSTITUTION_OTHER" varchar2(255), "FOREIGN_COURSE" varchar2(255), "FOREIGN_DISCIPLINE" varchar2(255), "FOREIGN_PROGRAM" varchar2(255), "SECONDARY_CLASS" varchar2(255), "INSTITUTION_ID" number, "PROGRAM_ID" number, "DEGREE_ID" number, "YEAR" number NOT NULL, CONSTRAINT "UQ_82f5714961315c03d2c060cc92e" UNIQUE ("UUID"), CONSTRAINT "PK_5dd4302a1b5231e8b44b980df68" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "TRAININGS" ADD CONSTRAINT "FK_43cf8d0129ca851eb02c31a1bd9" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "TRAININGS" ADD CONSTRAINT "FK_f1aabf5da5c284eab6d54e9c204" FOREIGN KEY ("COUNTRY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SKILLS" ADD CONSTRAINT "FK_265ab53ff98ca22e1b435d1f531" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SKILLS" ADD CONSTRAINT "FK_d76f9139abd671419e6c7752472" FOREIGN KEY ("CATEGORY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SKILLS" ADD CONSTRAINT "FK_6a83b3954ebcf02a7c830153d0e" FOREIGN KEY ("LEVEL_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" ADD CONSTRAINT "FK_427bdf368b9c1b2e327e6cdd983" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" ADD CONSTRAINT "FK_0e2103f07257f4edd4cfc1ca38d" FOREIGN KEY ("JOB_FAMILY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" ADD CONSTRAINT "FK_1f48051e7d24ac1718b5261b4d7" FOREIGN KEY ("JOB_TYPE_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" ADD CONSTRAINT "FK_edb2e1e315d992d2ac30babfb6f" FOREIGN KEY ("COUNTRY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "CERTIFICATIONS" ADD CONSTRAINT "FK_4a7049931ac195d2150e112e464" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "CERTIFICATIONS" ADD CONSTRAINT "FK_fda62a0081b564edeba64020b1c" FOREIGN KEY ("CATEGORY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "CERTIFICATIONS" ADD CONSTRAINT "FK_1253f59488c0b5fa8531ded3118" FOREIGN KEY ("TYPE_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_4d5fdb8da18520eda59c4917447" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_ae7c8883a0e35f85957c31e0a58" FOREIGN KEY ("COUNTRY_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_3f03fb7967b8c21d98e1a0d5baf" FOREIGN KEY ("LEVEL_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_453769bc42baa81b7081e48419d" FOREIGN KEY ("DISCIPLINE_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_7e14946036b0125bdd2e55eb791" FOREIGN KEY ("COURSE_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_8fd13ba6ca3cac304759735d4fc" FOREIGN KEY ("INSTITUTION_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_1205d8d00b17cf6e2ecad5c0249" FOREIGN KEY ("PROGRAM_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" ADD CONSTRAINT "FK_1d374048a6359a75d54261ce3cc" FOREIGN KEY ("DEGREE_ID") REFERENCES "BASE_RECORDS" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_1d374048a6359a75d54261ce3cc"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_1205d8d00b17cf6e2ecad5c0249"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_8fd13ba6ca3cac304759735d4fc"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_7e14946036b0125bdd2e55eb791"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_453769bc42baa81b7081e48419d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_3f03fb7967b8c21d98e1a0d5baf"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_ae7c8883a0e35f85957c31e0a58"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ACADEMICS" DROP CONSTRAINT "FK_4d5fdb8da18520eda59c4917447"`,
    );
    await queryRunner.query(
      `ALTER TABLE "CERTIFICATIONS" DROP CONSTRAINT "FK_1253f59488c0b5fa8531ded3118"`,
    );
    await queryRunner.query(
      `ALTER TABLE "CERTIFICATIONS" DROP CONSTRAINT "FK_fda62a0081b564edeba64020b1c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "CERTIFICATIONS" DROP CONSTRAINT "FK_4a7049931ac195d2150e112e464"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" DROP CONSTRAINT "FK_edb2e1e315d992d2ac30babfb6f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" DROP CONSTRAINT "FK_1f48051e7d24ac1718b5261b4d7"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" DROP CONSTRAINT "FK_0e2103f07257f4edd4cfc1ca38d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "JOB_EXPERIENCES" DROP CONSTRAINT "FK_427bdf368b9c1b2e327e6cdd983"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SKILLS" DROP CONSTRAINT "FK_6a83b3954ebcf02a7c830153d0e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SKILLS" DROP CONSTRAINT "FK_d76f9139abd671419e6c7752472"`,
    );
    await queryRunner.query(
      `ALTER TABLE "SKILLS" DROP CONSTRAINT "FK_265ab53ff98ca22e1b435d1f531"`,
    );
    await queryRunner.query(
      `ALTER TABLE "TRAININGS" DROP CONSTRAINT "FK_f1aabf5da5c284eab6d54e9c204"`,
    );
    await queryRunner.query(
      `ALTER TABLE "TRAININGS" DROP CONSTRAINT "FK_43cf8d0129ca851eb02c31a1bd9"`,
    );
    await queryRunner.query(`DROP TABLE "ACADEMICS"`);
    await queryRunner.query(`DROP TABLE "CERTIFICATIONS"`);
    await queryRunner.query(`DROP TABLE "JOB_EXPERIENCES"`);
    await queryRunner.query(`DROP TABLE "SKILLS"`);
    await queryRunner.query(`DROP TABLE "TRAININGS"`);
  }
}
