export enum eventType {
  RESET_PASSWORD = 'reset_password',
  ACCOUNT_CREATED = 'account_created',
  FORGOT_PASSWORD = 'forgot_password',
  INDIVIDUAL_WELCOME = 'individual_welcome',
  INDIVIDUAL_ACTIVATION = 'individual_activation',
  COMPANY_WELCOME = 'company_welcome',
  OPERATOR_WELCOME = 'operator_welcome',
  AGENCY_WELCOME = 'agency_welcome',
  INSTITUTION_WELCOME = 'institution_welcome',
  AUTH_OTP = 'auth-otp',
  SUG_WELCOME = 'sug_welcome',
  ADMIN_WELCOME = 'admin_welcome',
  VENDOR_WELCOME = 'vendor_welcome',
  AUDITOR_WELCOME = 'auditor_welcome',
}
