// Expanded to reflect NUS career paths
export enum AcademicRank {
  GRADUATE_ASSISTANT = 'GRADUATE_ASSISTANT',
  ASSISTANT_LECTURER = 'ASSISTANT_LECTURER',
  LECTURER_II = 'LECTURER_II',
  LECTURER_I = 'LECTURER_I',
  SENIOR_LECTURER = 'SENIOR_LECTURER',
  READER = 'READER', // Equivalent to Associate Professor
  ASSOCIATE_PROFESSOR = 'ASSOCIATE_PROFESSOR',
  PROFESSOR = 'PROFESSOR',
}
