export enum AccountTypeEnum {
  INDIVIDUAL = 'INDIVIDUAL',
  COMPANY = 'COMPANY',
  OPERATOR = 'OPERATOR',
  ADMIN = 'ADMIN',
  COMMUNITY_VENDOR = 'COMMUNITY_VENDOR',
  INSTITUTION = 'INSTITUTION',
  AUDITOR = 'AUDITOR',
}
