export enum AccountTypeEnum {
  INDIVIDUAL = 'INDIVIDUAL',
  DEPARTMENT = 'DEPARTMENT',
  SUG = 'SUG',
  ADMIN = 'ADMIN',
  COMMUNITY_VENDOR = 'COMMUNITY_VENDOR',
  INSTITUTION = 'INSTITUTION',
  AUDITOR = 'AUDITOR',
}
