export const departmentsDbSeed = [
  {
    id: 1,
    name: 'Corporate Communications & Zonal Coordinations',
    type: 'DIVISION',
    parentId: null,
  },
  {
    id: 2,
    name: 'Commercial Ventures',
    type: 'DIVISION',
    parentId: null,
  },
  {
    id: 3,
    name: 'ES Office/STA',
    type: 'DIVISION',
    parentId: null,
  },
  {
    id: 4,
    name: 'Strategy & Transformation Projects',
    type: 'DIVISION',
    parentId: null,
  },
  {
    id: 5,
    name: 'Internal Audit',
    type: 'DEPARTMENT',
    parentId: null,
  },
  {
    id: 6,
    name: 'Procurement',
    type: 'DEPARTMENT',
    parentId: null,
  },
  {
    id: 7,
    name: 'Finance & Personnel Management',
    type: 'DIRECTORATE',
    parentId: null,
  },
  {
    id: 8,
    name: 'NCDF & Treasury Management',
    type: 'DIVISION',
    parentId: 7,
  },
  {
    id: 9,
    name: 'Finance & Accounts',
    type: 'DIVISION',
    parentId: 7,
  },
  {
    id: 10,
    name: 'Human Resources',
    type: 'DIVISION',
    parentId: 7,
  },
  {
    id: 11,
    name: 'Corporate Services',
    type: 'DIRECTORATE',
    parentId: null,
  },
  {
    id: 12,
    name: 'Facilities & Logistics',
    type: 'DIVISION',
    parentId: 11,
  },
  {
    id: 13,
    name: 'Information & Communication Technology',
    type: 'DIVISION',
    parentId: 11,
  },
  {
    id: 14,
    name: 'H.S.S.E',
    type: 'DIVISION',
    parentId: 11,
  },
  {
    id: 15,
    name: 'Monitoring & Evaluation',
    type: 'DIRECTORATE',
    parentId: null,
  },
  {
    id: 16,
    name: 'Upstream',
    type: 'DIVISION',
    parentId: 15,
  },
  {
    id: 17,
    name: 'Midstream',
    type: 'DIVISION',
    parentId: 15,
  },
  {
    id: 18,
    name: 'Downstream',
    type: 'DIVISION',
    parentId: 15,
  },
  {
    id: 19,
    name: 'Quality Assurance',
    type: 'DIVISION',
    parentId: 15,
  },
  {
    id: 20,
    name: 'Planning Research & Statistics',
    type: 'DIRECTORATE',
    parentId: null,
  },
  {
    id: 21,
    name: 'Planning & Policy Development',
    type: 'DIVISION',
    parentId: 20,
  },
  {
    id: 22,
    name: 'Research, Statistics & Development',
    type: 'DIVISION',
    parentId: 20,
  },
  {
    id: 23,
    name: 'Research & Statistics',
    type: 'DEPARTMENT',
    parentId: 22,
  },
  {
    id: 24,
    name: 'Research & Development',
    type: 'DEPARTMENT',
    parentId: 22,
  },
  {
    id: 25,
    name: 'Project Certification & Authorization',
    type: 'DIRECTORATE',
    parentId: null,
  },
  {
    id: 26,
    name: 'Upstream',
    type: 'DIVISION',
    parentId: 25,
  },
  {
    id: 27,
    name: 'Midstream',
    type: 'DIVISION',
    parentId: 25,
  },
  {
    id: 28,
    name: 'Downstream',
    type: 'DIVISION',
    parentId: 25,
  },
  {
    id: 29,
    name: 'Capacity Building',
    type: 'DIRECTORATE',
    parentId: null,
  },
  {
    id: 30,
    name: 'Human Capital Development',
    type: 'DIVISION',
    parentId: 29,
  },
  {
    id: 31,
    name: 'Infrastructure Development',
    type: 'DIVISION',
    parentId: 29,
  },
  {
    id: 32,
    name: 'Legal Services',
    type: 'DIRECTORATE',
    parentId: null,
  },
  {
    id: 33,
    name: 'Corporate & Commercials',
    type: 'DIVISION',
    parentId: 32,
  },
  {
    id: 34,
    name: 'Commercials',
    type: 'DEPARTMENT',
    parentId: 33,
  },
  {
    id: 35,
    name: 'Governing Council & Corporate Affairs',
    type: 'DEPARTMENT',
    parentId: 33,
  },
  {
    id: 36,
    name: 'Enforcement & Litigation',
    type: 'DEPARTMENT',
    parentId: 33,
  },
];

export const departmentsNestedDbSeed = [
  {
    id: 1,
    name: 'Corporate Communications & Zonal Coordinations',
    type: 'DIVISION',
    parentId: null,
    children: [],
  },
  {
    id: 2,
    name: 'Commercial Ventures',
    type: 'DIVISION',
    parentId: null,
    children: [],
  },
  {
    id: 3,
    name: 'ES Office/STA',
    type: 'DIVISION',
    parentId: null,
    children: [],
  },
  {
    id: 4,
    name: 'Strategy & Transformation Projects',
    type: 'DIVISION',
    parentId: null,
    children: [],
  },
  {
    id: 5,
    name: 'Internal Audit',
    type: 'DEPARTMENT',
    parentId: null,
    children: [],
  },
  {
    id: 6,
    name: 'Procurement',
    type: 'DEPARTMENT',
    parentId: null,
    children: [],
  },
  {
    id: 7,
    name: 'Finance & Personnel Management',
    type: 'DIRECTORATE',
    parentId: null,
    children: [
      {
        id: 8,
        name: 'NCDF & Treasury Management',
        type: 'DIVISION',
        parentId: 7,
      },
      {
        id: 9,
        name: 'Finance & Accounts',
        type: 'DIVISION',
        parentId: 7,
      },
      {
        id: 10,
        name: 'Human Resources',
        type: 'DIVISION',
        parentId: 7,
      },
    ],
  },
  {
    id: 11,
    name: 'Corporate Services',
    type: 'DIRECTORATE',
    parentId: null,
    children: [
      {
        id: 12,
        name: 'Facilities & Logistics',
        type: 'DIVISION',
        parentId: 11,
      },
      {
        id: 13,
        name: 'Information & Communication Technology',
        type: 'DIVISION',
        parentId: 11,
      },
      {
        id: 14,
        name: 'H.S.S.E',
        type: 'DIVISION',
        parentId: 11,
      },
    ],
  },
  {
    id: 15,
    name: 'Monitoring & Evaluation',
    type: 'DIRECTORATE',
    parentId: null,
    children: [
      {
        id: 16,
        name: 'Upstream',
        type: 'DIVISION',
        parentId: 15,
      },
      {
        id: 17,
        name: 'Midstream',
        type: 'DIVISION',
        parentId: 15,
      },
      {
        id: 18,
        name: 'Downstream',
        type: 'DIVISION',
        parentId: 15,
      },
      {
        id: 19,
        name: 'Quality Assurance',
        type: 'DIVISION',
        parentId: 15,
      },
    ],
  },
  {
    id: 20,
    name: 'Planning Research & Statistics',
    type: 'DIRECTORATE',
    parentId: null,
    children: [
      {
        id: 21,
        name: 'Planning & Policy Development',
        type: 'DIVISION',
        parentId: 20,
      },
      {
        id: 22,
        name: 'Research, Statistics & Development',
        type: 'DIVISION',
        parentId: 20,
        children: [
          {
            id: 23,
            name: 'Research & Statistics',
            type: 'DEPARTMENT',
            parentId: 22,
          },
          {
            id: 24,
            name: 'Research & Development',
            type: 'DEPARTMENT',
            parentId: 22,
          },
        ],
      },
    ],
  },
  {
    id: 25,
    name: 'Project Certification & Authorization',
    type: 'DIRECTORATE',
    parentId: null,
    children: [
      {
        id: 26,
        name: 'Upstream',
        type: 'DIVISION',
        parentId: 25,
      },
      {
        id: 27,
        name: 'Midstream',
        type: 'DIVISION',
        parentId: 25,
      },
      {
        id: 28,
        name: 'Downstream',
        type: 'DIVISION',
        parentId: 25,
      },
    ],
  },
  {
    id: 29,
    name: 'Capacity Building',
    type: 'DIRECTORATE',
    parentId: null,
    children: [
      {
        id: 30,
        name: 'Human Capital Development',
        type: 'DIVISION',
        parentId: 29,
      },
      {
        id: 31,
        name: 'Infrastructure Development',
        type: 'DIVISION',
        parentId: 29,
      },
    ],
  },
  {
    id: 32,
    name: 'Legal Services',
    type: 'DIRECTORATE',
    parentId: null,
    children: [
      {
        id: 33,
        name: 'Corporate & Commercials',
        type: 'DIVISION',
        parentId: 32,
        children: [
          {
            id: 34,
            name: 'Commercials',
            type: 'DEPARTMENT',
            parentId: 33,
          },
          {
            id: 35,
            name: 'Governing Council & Corporate Affairs',
            type: 'DEPARTMENT',
            parentId: 33,
          },
          {
            id: 36,
            name: 'Enforcement & Litigation',
            type: 'DEPARTMENT',
            parentId: 33,
          },
        ],
      },
    ],
  },
];
