import { CreateInstitutionDto } from '@app/account/dto/institution/create-institution.dto';
import { UpdateInstitutionDto } from '@app/account/dto/institution/update-institution.dto';
import {
  CreateAgencyDto,
  CreateAuditorDto,
  CreateCompanyDto,
  CreateIndividualDto,
  CreateOperatorDto,
  UpdateAgencyDto,
  UpdateAuditorDto,
  UpdateCompanyDto,
  UpdateIndividualDto,
  UpdateOperatorDto,
} from './dto';
import { CreateCommunityVendorDto } from './dto/community-vendor/create-community-vendor.dto';
import { UpdateCommunityVendorDto } from './dto/community-vendor/update-community-vendor.dto';
import { AccountTypeEnum } from './enums';
// import { UpdateInstituionDto } from '@app/account/dto/institution/update-institution.dto';
// import { UpdateInstituionDto } from '@app/account/dto/institution/update-institution.dto';

type Options = {
  fillable: string[];
  relations: string[];
  searchable: string[];
  createDto: any;
  updateDto: any;
};

export type AccountTypeMapping = Record<AccountTypeEnum, Options>;
export const accountTypeMapping: AccountTypeMapping = {
  [AccountTypeEnum.INSTITUTION]: {
    fillable: [
      'name',
      'accountId',
      'institutionName',
      'institutionType',
      'registrationNumber',
      'dateOfEstablishment',
      'address',
      'contactNumber',
      'email',
      'website',
      'representativeName',
      'representativeDesignation',
    ],
    relations: [],
    searchable: [
      'institution.institutionName',
      'institution.institutionType',
      'institution.registrationNumber',
      'institution.dateOfEstablishment',
    ],
    createDto: CreateInstitutionDto,
    updateDto: UpdateInstitutionDto,
  },
  [AccountTypeEnum.INDIVIDUAL]: {
    fillable: [
      'firstName',
      'lastName',
      'otherNames',
      'isExpatriate',
      'dob',
      'gender',
      'phoneNumber',
      'countryId',
      'nationalityId',
      'altEmail',
      'altPhoneNumber',
      'address',
      'stateId',
      'cityResidence',
      'stateResidenceForeign',
      'stateResidenceId',
      'lgaId',
      'homeTown',
      'employmentStatus',
      'currentEmployer',
      'dateEmployed',
      'ninNumber',
      'accountId',
      'uuid',
      'competencyId',
    ],
    relations: ['country', 'nationality', 'state', 'lga', 'stateResidence'],
    searchable: [
      'users.firstName',
      'users.lastName',
      'individual.firstName',
      'individual.lastName',
      'individual.phoneNumber',
      'individual.competencyId',
      'users.email',
    ],
    createDto: CreateIndividualDto,
    updateDto: UpdateIndividualDto,
  },
  [AccountTypeEnum.AGENCY]: {
    fillable: [
      'firstName',
      'lastName',
      'position',
      'workflowGroups',
      'phoneNumber',
      'accountId',
      'uuid',
    ],
    relations: [],
    searchable: [
      'users.firstName',
      'users.lastName',
      'agency.firstName',
      'agency.lastName',
      'users.email',
    ],
    createDto: CreateAgencyDto,
    updateDto: UpdateAgencyDto,
  },
  [AccountTypeEnum.COMPANY]: {
    fillable: [
      'name',
      'rcNumber',
      'isOffshore',
      'email',
      'phoneNumber',
      'otherPhoneNumbers',
      'address',
      'businessCategoryId',
      'newFacilityId',
      'otherPhoneNumbers',
      'dprNumber',
      'nseStatus',
      'nseRegNo',
      'incorporationDate',
      'totalCompanyShares',
      'taxNumber',
      'facilityLocation',
      'facility',
      'staffStrengthLocal',
      'staffStrengthForeign',
      'staffStrengthForeignCount',
      'staffStrengthNigeriaCount',
      'nigerianOwnershipPercent',
      'accountId',
      'uuid',
      'isExternal',
      'remittanceId',
      'vendorRemittanceId',
    ],
    relations: ['businessCategory', 'newFacility'],
    searchable: [
      'company.name',
      'users.email',
      'company.phoneNumber',
      'company.rcNumber',
      'company.nogicNumber',
    ],
    createDto: CreateCompanyDto,
    updateDto: UpdateCompanyDto,
  },
  [AccountTypeEnum.OPERATOR]: {
    fillable: [
      'name',
      'email',
      'password',
      'rcNumber',
      'address',
      'businessCategoryId',
      'categoryId',
      'category',
      'phoneNumber',
      'businessCategory',
      'otherPhoneNumbers',
      'address',
      'businessCategoryId',
      'otherPhoneNumbers',
      'dprNumber',
      'nseStatus',
      'nseRegNo',
      'incorporationDate',
      'totalCompanyShares',
      'taxNumber',
      'facilityLocation',
      'facility',
      'staffStrengthLocal',
      'staffStrengthForeign',
      'staffStrengthForeignCount',
      'staffStrengthNigeriaCount',
      'nigerianOwnershipPercent',
      'accountId',
      'uuid',
      'remittanceId',
      'vendorRemittanceId',
    ],
    searchable: [
      'operator.name',
      'users.email',
      'operator.phoneNumber',
      'operator.rcNumber',
      'operator.nogicNumber',
    ],
    relations: ['category', 'businessCategory'],
    createDto: CreateOperatorDto,
    updateDto: UpdateOperatorDto,
  },
  [AccountTypeEnum.COMMUNITY_VENDOR]: {
    fillable: [
      'name',
      'email',
      'address',
      'phoneNumber',
      'accountId',
      'stateId',
      'nogicNumber',
    ],
    relations: ['state'],
    searchable: ['communityVendor.name', 'communityVendor.nogicNumber'],
    createDto: CreateCommunityVendorDto,
    updateDto: UpdateCommunityVendorDto,
  },
  [AccountTypeEnum.AUDITOR]: {
    fillable: ['firstName', 'lastName', 'email', 'phoneNumber', 'accountId'],
    relations: [],
    searchable: [
      'auditor.firstName',
      'auditor.lastName',
      'users.email',
      'auditor.email',
      'auditor.phoneNumber',
    ],
    createDto: CreateAuditorDto,
    updateDto: UpdateAuditorDto,
  },
};
